defmodule OpenApiMeilisearch.FacetSearchQuery do
  @moduledoc """
  Provides struct and type for a FacetSearchQuery
  """

  @type t :: %__MODULE__{
          attributes_to_search_on: [String.t()] | nil,
          exhaustive_facet_count: boolean | nil,
          facet_name: String.t(),
          facet_query: String.t() | nil,
          filter: map | nil,
          hybrid: OpenApiMeilisearch.HybridQuery.t() | nil,
          locales: [String.t()] | nil,
          matching_strategy: String.t(),
          q: String.t() | nil,
          ranking_score_threshold: number | nil,
          vector: [number] | nil
        }

  defstruct [
    :attributes_to_search_on,
    :exhaustive_facet_count,
    :facet_name,
    :facet_query,
    :filter,
    :hybrid,
    :locales,
    :matching_strategy,
    :q,
    :ranking_score_threshold,
    :vector
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      attributes_to_search_on: {:union, [[:string], :null]},
      exhaustive_facet_count: {:union, [:boolean, :null]},
      facet_name: :string,
      facet_query: {:union, [:string, :null]},
      filter: :map,
      hybrid: {:union, [{OpenApiMeilisearch.HybridQuery, :t}, :null]},
      locales:
        {:union,
         [
           [
             enum: [
               "af",
               "ak",
               "am",
               "ar",
               "az",
               "be",
               "bn",
               "bg",
               "ca",
               "cs",
               "da",
               "de",
               "el",
               "en",
               "eo",
               "et",
               "fi",
               "fr",
               "gu",
               "he",
               "hi",
               "hr",
               "hu",
               "hy",
               "id",
               "it",
               "jv",
               "ja",
               "kn",
               "ka",
               "km",
               "ko",
               "la",
               "lv",
               "lt",
               "ml",
               "mr",
               "mk",
               "my",
               "ne",
               "nl",
               "nb",
               "or",
               "pa",
               "fa",
               "pl",
               "pt",
               "ro",
               "ru",
               "si",
               "sk",
               "sl",
               "sn",
               "es",
               "sr",
               "sv",
               "ta",
               "te",
               "tl",
               "th",
               "tk",
               "tr",
               "uk",
               "ur",
               "uz",
               "vi",
               "yi",
               "zh",
               "zu",
               "afr",
               "aka",
               "amh",
               "ara",
               "aze",
               "bel",
               "ben",
               "bul",
               "cat",
               "ces",
               "dan",
               "deu",
               "ell",
               "eng",
               "epo",
               "est",
               "fin",
               "fra",
               "guj",
               "heb",
               "hin",
               "hrv",
               "hun",
               "hye",
               "ind",
               "ita",
               "jav",
               "jpn",
               "kan",
               "kat",
               "khm",
               "kor",
               "lat",
               "lav",
               "lit",
               "mal",
               "mar",
               "mkd",
               "mya",
               "nep",
               "nld",
               "nob",
               "ori",
               "pan",
               "pes",
               "pol",
               "por",
               "ron",
               "rus",
               "sin",
               "slk",
               "slv",
               "sna",
               "spa",
               "srp",
               "swe",
               "tam",
               "tel",
               "tgl",
               "tha",
               "tuk",
               "tur",
               "ukr",
               "urd",
               "uzb",
               "vie",
               "yid",
               "zho",
               "zul",
               "cmn"
             ]
           ],
           :null
         ]},
      matching_strategy: {:enum, ["last", "all", "frequency"]},
      q: {:union, [:string, :null]},
      ranking_score_threshold: {:union, [{:number, "double"}, :null]},
      vector: {:union, [[number: "float"], :null]}
    ]
  end
end
