defmodule OpenApiMeilisearch.LocalizedAttributesRuleView do
  @moduledoc """
  Provides struct and type for a LocalizedAttributesRuleView
  """

  @type t :: %__MODULE__{
          attributePatterns: OpenApiMeilisearch.AttributePatterns.t(),
          locales: [String.t()]
        }

  defstruct [:attributePatterns, :locales]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      attributePatterns: {OpenApiMeilisearch.AttributePatterns, :t},
      locales: [
        enum: [
          "af",
          "ak",
          "am",
          "ar",
          "az",
          "be",
          "bn",
          "bg",
          "ca",
          "cs",
          "da",
          "de",
          "el",
          "en",
          "eo",
          "et",
          "fi",
          "fr",
          "gu",
          "he",
          "hi",
          "hr",
          "hu",
          "hy",
          "id",
          "it",
          "jv",
          "ja",
          "kn",
          "ka",
          "km",
          "ko",
          "la",
          "lv",
          "lt",
          "ml",
          "mr",
          "mk",
          "my",
          "ne",
          "nl",
          "nb",
          "or",
          "pa",
          "fa",
          "pl",
          "pt",
          "ro",
          "ru",
          "si",
          "sk",
          "sl",
          "sn",
          "es",
          "sr",
          "sv",
          "ta",
          "te",
          "tl",
          "th",
          "tk",
          "tr",
          "uk",
          "ur",
          "uz",
          "vi",
          "yi",
          "zh",
          "zu",
          "afr",
          "aka",
          "amh",
          "ara",
          "aze",
          "bel",
          "ben",
          "bul",
          "cat",
          "ces",
          "dan",
          "deu",
          "ell",
          "eng",
          "epo",
          "est",
          "fin",
          "fra",
          "guj",
          "heb",
          "hin",
          "hrv",
          "hun",
          "hye",
          "ind",
          "ita",
          "jav",
          "jpn",
          "kan",
          "kat",
          "khm",
          "kor",
          "lat",
          "lav",
          "lit",
          "mal",
          "mar",
          "mkd",
          "mya",
          "nep",
          "nld",
          "nob",
          "ori",
          "pan",
          "pes",
          "pol",
          "por",
          "ron",
          "rus",
          "sin",
          "slk",
          "slv",
          "sna",
          "spa",
          "srp",
          "swe",
          "tam",
          "tel",
          "tgl",
          "tha",
          "tuk",
          "tur",
          "ukr",
          "urd",
          "uzb",
          "vie",
          "yid",
          "zho",
          "zul",
          "cmn"
        ]
      ]
    ]
  end
end
