defmodule OpenApiMeilisearch.SearchQuery do
  @moduledoc """
  Provides struct and type for a SearchQuery
  """

  @type t :: %__MODULE__{
          attributes_to_crop: [String.t()] | nil,
          attributes_to_highlight: [String.t()] | nil,
          attributes_to_retrieve: [String.t()] | nil,
          attributes_to_search_on: [String.t()] | nil,
          crop_length: integer,
          crop_marker: String.t(),
          distinct: String.t() | nil,
          facets: [String.t()] | nil,
          filter: map | nil,
          highlight_post_tag: String.t(),
          highlight_pre_tag: String.t(),
          hits_per_page: integer | nil,
          hybrid: OpenApiMeilisearch.HybridQuery.t() | nil,
          limit: integer,
          locales: [String.t()] | nil,
          matching_strategy: String.t(),
          offset: integer,
          page: integer | nil,
          q: String.t() | nil,
          ranking_score_threshold: number | nil,
          retrieve_vectors: boolean,
          show_matches_position: boolean,
          show_ranking_score: boolean,
          show_ranking_score_details: boolean,
          sort: [String.t()] | nil,
          vector: [number] | nil
        }

  defstruct [
    :attributes_to_crop,
    :attributes_to_highlight,
    :attributes_to_retrieve,
    :attributes_to_search_on,
    :crop_length,
    :crop_marker,
    :distinct,
    :facets,
    :filter,
    :highlight_post_tag,
    :highlight_pre_tag,
    :hits_per_page,
    :hybrid,
    :limit,
    :locales,
    :matching_strategy,
    :offset,
    :page,
    :q,
    :ranking_score_threshold,
    :retrieve_vectors,
    :show_matches_position,
    :show_ranking_score,
    :show_ranking_score_details,
    :sort,
    :vector
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      attributes_to_crop: {:union, [[:string], :null]},
      attributes_to_highlight: {:union, [[:string], :null]},
      attributes_to_retrieve: {:union, [[:string], :null]},
      attributes_to_search_on: {:union, [[:string], :null]},
      crop_length: :integer,
      crop_marker: :string,
      distinct: {:union, [:string, :null]},
      facets: {:union, [[:string], :null]},
      filter: :map,
      highlight_post_tag: :string,
      highlight_pre_tag: :string,
      hits_per_page: {:union, [:integer, :null]},
      hybrid: {:union, [{OpenApiMeilisearch.HybridQuery, :t}, :null]},
      limit: :integer,
      locales:
        {:union,
         [
           [
             enum: [
               "af",
               "ak",
               "am",
               "ar",
               "az",
               "be",
               "bn",
               "bg",
               "ca",
               "cs",
               "da",
               "de",
               "el",
               "en",
               "eo",
               "et",
               "fi",
               "fr",
               "gu",
               "he",
               "hi",
               "hr",
               "hu",
               "hy",
               "id",
               "it",
               "jv",
               "ja",
               "kn",
               "ka",
               "km",
               "ko",
               "la",
               "lv",
               "lt",
               "ml",
               "mr",
               "mk",
               "my",
               "ne",
               "nl",
               "nb",
               "or",
               "pa",
               "fa",
               "pl",
               "pt",
               "ro",
               "ru",
               "si",
               "sk",
               "sl",
               "sn",
               "es",
               "sr",
               "sv",
               "ta",
               "te",
               "tl",
               "th",
               "tk",
               "tr",
               "uk",
               "ur",
               "uz",
               "vi",
               "yi",
               "zh",
               "zu",
               "afr",
               "aka",
               "amh",
               "ara",
               "aze",
               "bel",
               "ben",
               "bul",
               "cat",
               "ces",
               "dan",
               "deu",
               "ell",
               "eng",
               "epo",
               "est",
               "fin",
               "fra",
               "guj",
               "heb",
               "hin",
               "hrv",
               "hun",
               "hye",
               "ind",
               "ita",
               "jav",
               "jpn",
               "kan",
               "kat",
               "khm",
               "kor",
               "lat",
               "lav",
               "lit",
               "mal",
               "mar",
               "mkd",
               "mya",
               "nep",
               "nld",
               "nob",
               "ori",
               "pan",
               "pes",
               "pol",
               "por",
               "ron",
               "rus",
               "sin",
               "slk",
               "slv",
               "sna",
               "spa",
               "srp",
               "swe",
               "tam",
               "tel",
               "tgl",
               "tha",
               "tuk",
               "tur",
               "ukr",
               "urd",
               "uzb",
               "vie",
               "yid",
               "zho",
               "zul",
               "cmn"
             ]
           ],
           :null
         ]},
      matching_strategy: {:enum, ["last", "all", "frequency"]},
      offset: :integer,
      page: {:union, [:integer, :null]},
      q: {:union, [:string, :null]},
      ranking_score_threshold: {:union, [{:number, "double"}, :null]},
      retrieve_vectors: :boolean,
      show_matches_position: :boolean,
      show_ranking_score: :boolean,
      show_ranking_score_details: :boolean,
      sort: {:union, [[:string], :null]},
      vector: {:union, [[number: "float"], :null]}
    ]
  end
end
