defmodule OpenApiMeilisearch.SearchQueryWithIndex do
  @moduledoc """
  Provides struct and type for a SearchQueryWithIndex
  """

  @type t :: %__MODULE__{
          attributesToCrop: [String.t()] | nil,
          attributesToHighlight: [String.t()] | nil,
          attributesToRetrieve: [String.t()] | nil,
          attributesToSearchOn: [String.t()] | nil,
          cropLength: integer,
          cropMarker: String.t(),
          distinct: String.t() | nil,
          facets: [String.t()] | nil,
          federationOptions: OpenApiMeilisearch.FederationOptions.t() | nil,
          filter: map | nil,
          highlightPostTag: String.t(),
          highlightPreTag: String.t(),
          hitsPerPage: integer | nil,
          hybrid: OpenApiMeilisearch.HybridQuery.t() | nil,
          indexUid: String.t(),
          limit: integer | nil,
          locales: [String.t()] | nil,
          matchingStrategy: String.t(),
          offset: integer | nil,
          page: integer | nil,
          q: String.t() | nil,
          rankingScoreThreshold: number | nil,
          retrieveVectors: boolean,
          showMatchesPosition: boolean,
          showRankingScore: boolean,
          showRankingScoreDetails: boolean,
          sort: [String.t()] | nil,
          vector: [number] | nil
        }

  defstruct [
    :attributesToCrop,
    :attributesToHighlight,
    :attributesToRetrieve,
    :attributesToSearchOn,
    :cropLength,
    :cropMarker,
    :distinct,
    :facets,
    :federationOptions,
    :filter,
    :highlightPostTag,
    :highlightPreTag,
    :hitsPerPage,
    :hybrid,
    :indexUid,
    :limit,
    :locales,
    :matchingStrategy,
    :offset,
    :page,
    :q,
    :rankingScoreThreshold,
    :retrieveVectors,
    :showMatchesPosition,
    :showRankingScore,
    :showRankingScoreDetails,
    :sort,
    :vector
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      attributesToCrop: {:union, [[:string], :null]},
      attributesToHighlight: {:union, [[:string], :null]},
      attributesToRetrieve: {:union, [[:string], :null]},
      attributesToSearchOn: {:union, [[:string], :null]},
      cropLength: :integer,
      cropMarker: :string,
      distinct: {:union, [:string, :null]},
      facets: {:union, [[:string], :null]},
      federationOptions: {:union, [{OpenApiMeilisearch.FederationOptions, :t}, :null]},
      filter: :map,
      highlightPostTag: :string,
      highlightPreTag: :string,
      hitsPerPage: {:union, [:integer, :null]},
      hybrid: {:union, [{OpenApiMeilisearch.HybridQuery, :t}, :null]},
      indexUid: :string,
      limit: {:union, [:integer, :null]},
      locales:
        {:union,
         [
           [
             enum: [
               "af",
               "ak",
               "am",
               "ar",
               "az",
               "be",
               "bn",
               "bg",
               "ca",
               "cs",
               "da",
               "de",
               "el",
               "en",
               "eo",
               "et",
               "fi",
               "fr",
               "gu",
               "he",
               "hi",
               "hr",
               "hu",
               "hy",
               "id",
               "it",
               "jv",
               "ja",
               "kn",
               "ka",
               "km",
               "ko",
               "la",
               "lv",
               "lt",
               "ml",
               "mr",
               "mk",
               "my",
               "ne",
               "nl",
               "nb",
               "or",
               "pa",
               "fa",
               "pl",
               "pt",
               "ro",
               "ru",
               "si",
               "sk",
               "sl",
               "sn",
               "es",
               "sr",
               "sv",
               "ta",
               "te",
               "tl",
               "th",
               "tk",
               "tr",
               "uk",
               "ur",
               "uz",
               "vi",
               "yi",
               "zh",
               "zu",
               "afr",
               "aka",
               "amh",
               "ara",
               "aze",
               "bel",
               "ben",
               "bul",
               "cat",
               "ces",
               "dan",
               "deu",
               "ell",
               "eng",
               "epo",
               "est",
               "fin",
               "fra",
               "guj",
               "heb",
               "hin",
               "hrv",
               "hun",
               "hye",
               "ind",
               "ita",
               "jav",
               "jpn",
               "kan",
               "kat",
               "khm",
               "kor",
               "lat",
               "lav",
               "lit",
               "mal",
               "mar",
               "mkd",
               "mya",
               "nep",
               "nld",
               "nob",
               "ori",
               "pan",
               "pes",
               "pol",
               "por",
               "ron",
               "rus",
               "sin",
               "slk",
               "slv",
               "sna",
               "spa",
               "srp",
               "swe",
               "tam",
               "tel",
               "tgl",
               "tha",
               "tuk",
               "tur",
               "ukr",
               "urd",
               "uzb",
               "vie",
               "yid",
               "zho",
               "zul",
               "cmn"
             ]
           ],
           :null
         ]},
      matchingStrategy: {:enum, ["last", "all", "frequency"]},
      offset: {:union, [:integer, :null]},
      page: {:union, [:integer, :null]},
      q: {:union, [:string, :null]},
      rankingScoreThreshold: {:union, [{:number, "double"}, :null]},
      retrieveVectors: :boolean,
      showMatchesPosition: :boolean,
      showRankingScore: :boolean,
      showRankingScoreDetails: :boolean,
      sort: {:union, [[:string], :null]},
      vector: {:union, [[number: "float"], :null]}
    ]
  end
end
